#!/bin/sh

rm -rf build
mkdir build

_kernel=build/GENERIC.CDROOT

cat ./GENERIC.3.99.16 | sed '/^config/d;/SCSI/d' > $_kernel
cat ./kern.no-conf >> $_kernel


/build/netbsd-3.99.x/tools/i386/bin/nbconfig -s ~/src/netbsd/dev/src/sys \
	-b ./build $_kernel
cd ./build
/build/netbsd-3.99.x/tools/i386/bin/nbmake-i386 -j4 depend
/build/netbsd-3.99.x/tools/i386/bin/nbmake-i386 -j4 
