#!/bin/sh
#
# $NetBSD: mountcritlocal,v 1.7 2002/04/29 12:29:53 lukem Exp $
#

# PROVIDE: mountmfs
# REQUIRE: root
# BEFORE:  mountcritlocal

. /etc/rc.subr

name="mountmfs"
start_cmd="mountmfs_start"
stop_cmd=":"

mountmfs_start()
{
	PWD=`/bin/pwd`

	mount -a -t mfs > /dev/null 2>&1
	echo "Copying /altvar -> /var"
	(cd /altvar && /bin/pax -rw -pe * /var)

	/usr/bin/touch /var/db/dhcpd.leases
	cd $PWD
}

load_rc_config $name
run_rc_command "$1"
