#!/bin/sh
#
# $NetBSD$
#

# BEFORE: named dhcpd nfsd rpcbind mountd dhcpcd
# REQUIRE: network mountmfs

echo "Configuring network interface..."

for i in `/sbin/ifconfig -l`; do
	case $i in
		sl*)
		;;

		vpn*)
		;;

		ppp*)
		;;

		fwip*)
		;;

		an*|ath*|atu*|atw*|bwfm*|otus*|ral*|rum*|rtw*|run*|upgt*|ural*|urtw*|wi*|zyd*)
		# ignore 801.11 wireless adapters
		;;

		*)
		echo "Found interface $i"
		/sbin/ifconfig $i 10.0.0.254
		exit 0
		;;
	esac
done
