#!/bin/sh
#
# $NetBSD: mountcritlocal,v 1.7 2002/04/29 12:29:53 lukem Exp $
#

# PROVIDE: mountmfs
# REQUIRE: root
# BEFORE:  mountcritlocal

. /etc/rc.subr

name="mountmfs"
start_cmd="mountmfs_start"
stop_cmd=":"

printmsg()
{
	_category="$1"
	_message="$2"

	if [ ! -f /dev/lcdpanel0 ]; then
		cd /dev && ./MAKEDEV lcdpanel
	fi

	echo "$_message"
	printf "%-16s%-16s" "$_category" "  $_message" > /dev/lcdpanel0
}

mountmfs_start()
{
	PWD=`/bin/pwd`

	printmsg "[Starting up]" "Create /dev/*"

	cd /dev
	/bin/sh ./MAKEDEV all >/dev/null 2>&1
	cd $PWD

	printmsg "[Starting up]" "Unpack /var/*"

	mount -a -t nonfs >/dev/null 2>&1

	cd /altvar
	/bin/pax -rw -pe * /var
	cd $PWD
}

load_rc_config $name
run_rc_command "$1"
